### PR TITLE
Update quickstart-custom-categories.md

### PR DESCRIPTION
**Pull request by jinruishao**

### CODE REVIEW

**Comment by jinruishao** [comment]
#sign-off

**Comment by jinruishao** [comment]
#sign-off

**Comment by jinruishao** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@jinruishao - since you have access to the private repo, you need to open PRs there for any changes you'd like to make

cc: @PatrickFarley 

> Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.
> 
> After you make your changes in the private repo, review the articles on staging, and fix any validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged. 
> 
> Read about [authors working in the public repo](https://review.docs.microsoft.com/help/contribute/contribute-authors-in-public-repo?branch=main) for more information. 
>

We'll close this PR. Thank you.

**Pull request closed without merging**
